$:.unshift(File.join(File.dirname(__FILE__), 'lib'))
require "chef-server-api"

source :rubygems

gem 'bunny'
gem 'uuidtools'
gem 'ohai'
gem 'thin'
gem 'dep_selector'

merb_gems_version = "1.1.3"
gem "merb-core", merb_gems_version
gem "merb-assets", merb_gems_version
gem "merb-haml", merb_gems_version
gem "merb-helpers", merb_gems_version
gem "merb-param-protection", merb_gems_version

gem "chef", ChefServerApi::VERSION, :require => false # load individual parts as needed
gem "chef-solr", ChefServerApi::VERSION, :require => "chef/solr"

group :test do
  gem "rake"

  gem "rspec", "~> 2.5"
  gem "webrat"
  gem "webrat-rspec-rails"
end

group(:prod) do
  gem "unicorn", "~> 2.0.0"
end
